version: "2"

engines:
  eslint:
    enabled: true
    channel: eslint-5
    config:
      config: .eslintrc.js
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  duplication:
    enabled: false
  structure:
    enabled: false
