version: "2"
checks:
  method-lines:
    config:
      threshold: 50
engines:
  eslint:
    enabled: true
    channel: eslint-5
    config:
      config: .eslintrc.js
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  duplication:
    enabled: false

exclude_paths:
  - .cache/*
  - node_modules/*
  - packages/node-service/*
  - packages/client/node_modules/*
  - packages/client/.cache/*
  - packages/client/coverage/*
